# Generated by Django 3.0.8 on 2020-07-10 16:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='teléfono 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='teléfono 3 (opcional)'),
        ),
    ]
